# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 13:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topperApp', '0006_addalbum_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='addreview',
            unique_together=set([('album', 'username')]),
        ),
    ]
